export const AppChannel =
{
    GetAppSetting : "DBMESSAGE_GETAPPSETTING",
    SaveAppSetting : "DBMESSAGE_SAVEAPPSETTING",
    SaveStartupSetting: "APP_SAVE_STARTUP_SETTING",
    InitTray: "APP_INITTRAY",
    ShowOpenDialog: "APP_SHOWOPENDIALOG",
    ShowSaveDialog: "APP_SHOWSAVEDIALOG",
    CustomHyperlink: "APP_CUSTOMHYPERLINK",
    OpenHyperlink: "APP_CUSTOMHYPERLINK",
    CommandMin: "APP_COMMAND_MIN",
    CommandMax: "APP_COMMAND_MAX",
    CommandClose: "APP_COMMAND_CLOSE",
    Tool_SaveFile: "APP_TOOL_SAVEFILE",
    Tool_ClearFolder: "APP_TOOL_CLEARFOLDER",
    Tool_SupportSaveFile: "APP_TOOL_SUPPORTSAVEFILE",
    Tool_OpenFile: "APP_TOOL_OPENFILE",
    GetAvailableTranslations:  "APP_GETAVAILABLETRANSLATIONS",
    GetVersion: "APP_GET_VERSION",
    GetVersionFileUrl:  "APP_GETVERSIONFILEURL",
    GetCORE2VersionFileUrl:  "APP_GETCORE2VERSIONFILEURL",
    GetBuildVersion:  "APP_GET_BUILDVERSION",
    GetDownloadedFirmwareUpdaters: 'APP_GETDOWNLOADEDFIRMWAREUPDATERS',
    BeginFirmwareDownloads: 'APP_BEGINFIRMWAREDOWNLOADS',
    BeginFirmwareUpdates: 'APP_BEGINFIRMWAREUPDATES',
    ShowDebug:  "APP_SHOW_DEBUG",

    Login: "APP_LOGIN",
    Logout: "APP_LOGOUT",
    IsLoggedIn: "APP_ISLOGGEDIN",
    GetProfile: "APP_GETPROFILE",
    ChangePassword: "APP_CHANGEPASSWORD",
    GetCloudDeviceProfiles: "APP_GETDEVICEPROFILES",
    CreateCloudDeviceProfile: "APP_CREATEDEVICEPROFILE",
    DeleteCloudDeviceProfile: "APP_DELETEDEVICEPROFILE",
    GetAllCloudDevicesProfiles: "APP_GETALLDEVICEPROFILES",
    SetFirmwareOverrides: "APP_SET_FIRMWARE_OVERRIDES",

    Tool_DownloadFile: "APP_TOOL_DOWNLOADFILE",
    Tool_CancelDownload: "APP_TOOL_CANCELDOWNLOAD"
};